apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-arm64-
  namespace: smc-cicd
spec:
  pipelineRef:
    name: build-image-pipeline
  params:
    - name: repo
      value: timgluz/smcprober
    - name: image
      value: tauho/smcprober:latest
    - name: platform
      value: linux/arm64

  # Apply node selector to ALL pods including affinity-assistant
  taskRunTemplate:
    podTemplate:
      nodeSelector:
        kubernetes.io/arch: arm64
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: dockerconfig
      secret:
        secretName: docker-config
  taskRunSpecs:
    - pipelineTaskName: fetch-source
      podTemplate:
        nodeSelector:
          kubernetes.io/arch: arm64
    - pipelineTaskName: build-docker
      podTemplate:
        nodeSelector:
          kubernetes.io/arch: arm64
