apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-multiarch-image-
  namespace: smc-cicd
spec:
  pipelineRef:
    name: build-multiarch-image
  params:
    - name: repo
      value: timgluz/smcprober
    - name: revision
      value: main
    - name: image
      value: tauho/smcprober:latest
  workspaces:
    - name: dockerconfig
      secret:
        secretName: docker-config
  taskRunSpecs:
    - pipelineTaskName: build-amd64
      podTemplate:
        nodeSelector:
          kubernetes.io/arch: amd64
    - pipelineTaskName: build-arm64
      podTemplate:
        nodeSelector:
          kubernetes.io/arch: arm64
