apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ include "helm.name" . }}-amconfig
  namespace: {{ $.Values.namespace }}
spec:
  route:
    receiver: 'default-receiver'
    groupBy: ['alertname', 'cluster', 'service']
    groupWait: {{ .Values.alertmanager.groupWait | default "60s" }}
    groupInterval: {{ .Values.alertmanager.groupInterval | default "5m" }}
    repeatInterval: {{ .Values.alertmanager.repeatInterval | default "12h" }}
    # Child routes for specific alerts
    routes:
    - receiver: 'on-call-receiver'
      matchers:
      - name: notify
        value: team_on_call
        matchType: '='
      groupWait: 30s
      repeatInterval: 5m
    - receiver: 'critical-receiver'
      matchers:
      - name: severity
        value: critical
        matchType: '='
      groupWait: 10s
      repeatInterval: 5m

  receivers:
  - name: 'default-receiver'
    webhookConfigs:
    - url: {{ .Values.alertmanager.webhooks.default | quote }}
      sendResolved: true
  - name: 'critical-receiver'
    webhookConfigs:
    - url: {{ .Values.alertmanager.webhooks.critical | quote }}
      sendResolved: true
  - name: 'on-call-receiver'
    webhookConfigs:
    - url: {{ .Values.alertmanager.webhooks.on_call | quote }}
      sendResolved: true


