apiVersion: v1
kind: ConfigMap
metadata:
  name: smcprober-config
  namespace: "{{ .Values.namespace }}"
  labels: {{- include "helm.labels" . | nindent 4 }}
data:
  config.json: |
{{ .Values.config | indent 4 }}
