apiVersion: v1
kind: Secret
metadata:
  name: smcprober-secret
  namespace: "{{ .Values.namespace }}"
  labels: {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
  env: {{ .Values.secret.env | b64enc }}
